DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
  ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
  FIRST_NAME VARCHAR(64) NOT NULL,
  LAST_NAME VARCHAR(64) NOT NULL,
  PHONE VARCHAR(64) NOT NULL,
  SEX VARCHAR(64) NOT NULL
);